apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoruba-language-api
  namespace: yoruba-api
  labels:
    app: yoruba-language-api
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yoruba-language-api
  template:
    metadata:
      labels:
        app: yoruba-language-api
        version: v1.0.0
    spec:
      containers:
        - name: api
          image: yoruba-language-api:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: yoruba-api-secrets
                  key: database-url
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: yoruba-api-secrets
                  key: api-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: yoruba-api-secrets
                  key: openai-api-key
            - name: AI_MODEL
              value: "gpt-4o"
            - name: DEBUG
              value: "false"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: yoruba-language-api-service
  namespace: yoruba-api
spec:
  selector:
    app: yoruba-language-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yoruba-language-api-ingress
  namespace: yoruba-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
    - hosts:
        - api.yoruba-language.com
      secretName: yoruba-api-tls
  rules:
    - host: api.yoruba-language.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yoruba-language-api-service
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yoruba-api-config
  namespace: yoruba-api
data:
  cors-origins: "https://yoruba-language.com,https://www.yoruba-language.com"
  rate-limit-per-minute: "60"
---
apiVersion: v1
kind: Secret
metadata:
  name: yoruba-api-secrets
  namespace: yoruba-api
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: cG9zdGdyZXNxbDovL3lvcnViYV91c2VyOnlvcnViYV9wYXNzd29yZEBwb3N0Z3Jlczo1NDMyL3lvcnViYV9hcGk=
  api-key: eW91cmFwaWtleTEyMw==
  openai-api-key: c2stcHJvai16b1cxT3YzUEdEWlhGZkJpdXE5cVhWWHVkbnVKNVd0b21fQ3NWVXFzMjVHVWREZWo3ZEMzZ25iQkUxM0IyUDZHSG1EbnpmS2trdjZUM0JsbGtGSkxCTW5hazhfM1d3VnZGc3FiQXYqdDRnRTNlVmogMDZ2Qmd3Mms5ODc3SVFRM2dabTFRVmY0bXdDMVI3OEF3TDVDUi1idkR6SXVFQQ==
